/**
 * Layers managed-provider adapter (examples/extensions/layers-growth). Fake transport, effect
 * vectors, quote checks, job ledger, onboarding contract, and host routes. No live client.
 */
export {
  LAYERS_DELIVER_TOOL,
  LAYERS_MCP_ENDPOINT,
  LAYERS_PROVIDER_ID,
  LAYERS_RECORDED_RESOURCES,
  LAYERS_RECORDED_TOOLS,
  LAYERS_RENDER_TOOL,
  createFakeLayersTransport,
  createLiveLayersTransportDescriptor,
  detectToolDrift,
  quoteArgumentsDigest,
  type FakeLayersResponse,
  type FakeLayersScript,
  type FakeLayersTransport,
  type LayersArtifact,
  type LayersBilling,
  type LayersCallResult,
  type LayersJobRead,
  type LayersJobState,
  type LayersQuote,
  type LayersToolDrift,
  type LayersToolListing,
  type LayersTransport,
  type LayersTransportKind,
  type LiveLayersTransportDescriptor,
} from "./transport.js";
export {
  LAYERS_DOCUMENTED_RENDER_CREDITS,
  LAYERS_OPERATION_EFFECTS,
  LAYERS_OPERATION_IDS,
  assertWithinApprovedCredits,
  effectVectorFor,
  requiredActionClass,
  verifyQuote,
  type LayersEffectVector,
  type LayersOperationId,
  type QuoteVerificationOptions,
} from "./effects.js";
export {
  LayersJobLedger,
  isCompletedArtifact,
  isReviewed,
  type LayersJobEntry,
  type LayersJobEvent,
  type LayersJobRequest,
  type LayersLedgerState,
  type LayersPublicationReceipt,
  type LayersReconciliation,
  type LayersReviewRecord,
} from "./jobs.js";
export {
  LAYERS_MCP_CONFIG_FILE,
  LAYERS_ONBOARDING_CONTRACT,
  LAYERS_ONBOARDING_FILES,
  LAYERS_PROJECT_FILE,
  LAYERS_SKILL_FILE,
  assertBriefMatchesIntent,
  checkBinding,
  inspectRepositoryForOnboarding,
  type LayersBindingCheck,
  type LayersOnboardingContract,
  type LayersOnboardingInspection,
  type LayersProviderProject,
  type LayersSelectedConnection,
} from "./onboarding.js";
export {
  LAYERS_CREATIVE_FORMATS,
  LAYERS_DRAFT_REQUEST_PATH,
  LAYERS_IMPLEMENTATION_IDS,
  LAYERS_READ_REQUEST_PATH,
  LAYERS_ROUTE_ARTIFACTS,
  assertNoPublicationArguments,
  createLayersDraftCreativeRoute,
  createLayersReadRoutes,
  createLayersRoutes,
  jobConsistentWithOutput,
  parseDraftCreativeInput,
  parseReadInput,
  renderArguments,
  type LayersCreativeBrief,
  type LayersCreativeFormat,
  type LayersDraftCreativeInput,
  type LayersEvidence,
  type LayersJobOutput,
  type LayersReadInput,
  type LayersRouteOptions,
} from "./route.js";
