#!/usr/bin/env node
/**
 * install-schedule.ts — writes (or removes) an OS-level schedule that invokes a business
 * workspace's scheduled session (KTD1: OS cron/launchd as the trigger, vendor schedulers as
 * interchangeable alternates). Mirrors tooling/install-hooks.ts's CLI shape and safety posture:
 * DEFAULT IS --dry-run (prints what would be installed, touches nothing); --apply is required to
 * touch the real system (crontab / launchctl). --apply is never invoked from this session or from
 * any fixture — checks/verification/fixtures/adapters.fixtures.ts asserts generated content only, via the
 * pure render/apply functions below, never against the real crontab or a real LaunchAgents file.
 *
 * Usage:
 *   tsx adapters/install-schedule.ts --workspace <dir> --runtime claude|codex|cursor \
 *       --schedule "(every 30 min, 5-field cron)" --brief <path/to/brief.json> [--mechanism cron|launchd] \
 *       [--wall-clock-seconds 1800] [--skill-root <path>] [--apply --approval <scheduled-autonomy-approval-id>] [--uninstall]
 */
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import { expandHome, flagBoolean, flagNumber, flagString, parseFlags } from "../tooling/lib/launch-state.js";
import { resolveSkillRoot } from "../tooling/lib/skill-root.js";
import { isMainModule } from "../kernel/lib/cli.js";
import { founderFacingRuntimeIds, type RuntimeId } from "./profile.js";
import { loadWorkspaceCatalog, renderCatalogRefusal } from "../kernel/session/catalog-contract.js";
import { acquireLock, releaseLock } from "../kernel/reducer/lock.js";
import { loadRunState } from "../kernel/engine/runstate.js";

const defaultSkillRoot = resolveSkillRoot(import.meta.url);

export type ScheduleMechanism = "cron" | "launchd";

export const scheduledAutonomyWorkflowId = "workflow.operations.scheduled-autonomy-installation";
export const scheduledAutonomyApprovalId = `${scheduledAutonomyWorkflowId}.approval.1`;

export interface ScheduleOptions {
  readonly workspaceDir: string;
  readonly runtime: RuntimeId;
  readonly schedule: string;
  readonly briefPath: string;
  readonly wallClockSeconds: number;
  readonly skillRoot: string;
  readonly wrapperPath: string;
  readonly logPath: string;
  readonly workspaceSlug: string;
}

// --- pure rendering (fixture-safe: no filesystem, no subprocess) ----------------------------

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

/** file:// import specifier a generated .mts wrapper uses to reach this skill's adapter modules from inside a business workspace. */
function importSpecifier(skillRoot: string, relativeModulePath: string): string {
  return pathToFileURL(path.join(skillRoot, relativeModulePath)).href;
}

export function renderWrapperScript(options: ScheduleOptions): string {
  const profileImport = importSpecifier(options.skillRoot, `adapters/${options.runtime}.ts`);
  const sharedImport = importSpecifier(options.skillRoot, "adapters/profile.ts");
  const compatibilityImport = importSpecifier(options.skillRoot, "kernel/session/catalog-contract.ts");
  const creatorName = `create${capitalize(options.runtime)}Profile`;
  return `#!/usr/bin/env -S tsx
// GENERATED by adapters/install-schedule.ts for workspace ${options.workspaceDir} / runtime ${options.runtime}.
// Do not edit by hand — reinstall (npm exec tsx adapters/install-schedule.ts ... --apply) to regenerate.
import { spawnSync } from "node:child_process";
import { ${creatorName} } from ${JSON.stringify(profileImport)};
import { wrapWithWallClock } from ${JSON.stringify(sharedImport)};
import { loadWorkspaceCatalog, renderCatalogRefusal } from ${JSON.stringify(compatibilityImport)};

const compatible = loadWorkspaceCatalog(${JSON.stringify(options.workspaceDir)});
if (!compatible.ok) {
  console.error(renderCatalogRefusal(compatible.refusal));
  process.exit(1);
}

const sessionId = \`sched-\${new Date().toISOString().replace(/[:.]/g, "-")}\`;
const profile = ${creatorName}();
const headless = profile.buildHeadlessCommand({
  workspaceDir: ${JSON.stringify(options.workspaceDir)},
  briefPath: ${JSON.stringify(options.briefPath)},
  sessionId,
  wallClockSeconds: ${options.wallClockSeconds},
  maxConcurrency: profile.maxConcurrency,
});
const wrapped = wrapWithWallClock(headless, ${options.wallClockSeconds});
if (wrapped.enforcementGap) console.error(\`wall-clock: \${wrapped.enforcementGap}\`);
const result = spawnSync(wrapped.command, [...wrapped.args], { stdio: "inherit", cwd: ${JSON.stringify(options.skillRoot)} });
process.exit(result.status ?? 1);
`;
}

export function crontabSignature(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">): string {
  return `b2c:${options.workspaceSlug}:${options.runtime}`;
}

function workspaceCrontabSignature(workspaceSlug: string): string {
  return `b2c:${workspaceSlug}:`;
}

function crontabTag(line: string): string | undefined {
  return /(?:^|\s)#\s+(b2c:[^\s#]+)\s*$/u.exec(line)?.[1];
}

/** Read-only state check for the managed entry; foreign crontab lines are ignored. */
export function crontabHasSignature(existingContent: string, signature: string): boolean {
  return existingContent.split(/\r?\n/u).some((line) => crontabTag(line) === signature);
}

/** Exact managed-line readback; a matching workspace/runtime tag alone is not enough after a concurrent edit. */
export function crontabHasExactLine(existingContent: string, expectedLine: string): boolean {
  return existingContent.split(/\r?\n/u).some((line) => line === expectedLine);
}

/** Readback for every runtime variant owned by one workspace. */
export function crontabHasWorkspaceSignature(existingContent: string, workspaceSlug: string): boolean {
  const prefix = workspaceCrontabSignature(workspaceSlug);
  return existingContent.split(/\r?\n/u).some((line) => {
    const tag = crontabTag(line);
    return tag !== undefined && tag.startsWith(prefix) && tag.length > prefix.length;
  });
}

export function renderCrontabLine(options: ScheduleOptions): string {
  return `${options.schedule} /usr/bin/env tsx ${options.wrapperPath} >> ${options.logPath} 2>&1 # ${crontabSignature(options)}`;
}

/** Removes only lines tagged with this workspace+runtime's signature; every other line (including a foreign crontab's own entries) is untouched. */
export function filterCrontabLines(existingLines: readonly string[], signature: string): string[] {
  return existingLines.filter((line) => crontabTag(line) !== signature);
}

export function applyCrontabInstall(existingContent: string, options: ScheduleOptions): { nextContent: string; line: string } {
  const lines = existingContent.split("\n").filter((line) => line.length > 0);
  const prefix = workspaceCrontabSignature(options.workspaceSlug);
  const withoutOurs = lines.filter((line) => {
    const tag = crontabTag(line);
    return tag === undefined || !tag.startsWith(prefix) || tag.length === prefix.length;
  });
  const line = renderCrontabLine(options);
  return { nextContent: `${[...withoutOurs, line].join("\n")}\n`, line };
}

/** The exact reverse of applyCrontabInstall for the workspace: removes managed runtime variants, leaves foreign lines untouched. */
export function applyCrontabUninstall(existingContent: string, options: ScheduleOptions): { nextContent: string; removed: string[] } {
  const lines = existingContent.split("\n").filter((line) => line.length > 0);
  const signature = workspaceCrontabSignature(options.workspaceSlug);
  const removed = lines.filter((line) => {
    const tag = crontabTag(line);
    return tag !== undefined && tag.startsWith(signature) && tag.length > signature.length;
  });
  const kept = lines.filter((line) => !removed.includes(line));
  return { nextContent: kept.length > 0 ? `${kept.join("\n")}\n` : "", removed };
}

export type CronToLaunchdTranslation =
  { kind: "interval"; seconds: number } | { kind: "calendar"; hour: number; minute: number } | { kind: "unsupported"; reason: string };

/**
 * launchd has no native cron-expression support. This translates the two common shapes a founder
 * or the onboarding console would actually produce ("every N minutes", "daily at H:M"); anything
 * else is reported as unsupported rather than silently approximated.
 */
export function translateCronToLaunchd(schedule: string): CronToLaunchdTranslation {
  const fields = schedule.trim().split(/\s+/);
  if (fields.length !== 5) return { kind: "unsupported", reason: `expected a 5-field cron expression, got "${schedule}"` };
  const [minute, hour, dom, month, dow] = fields as [string, string, string, string, string];
  if (dom === "*" && month === "*" && dow === "*") {
    const everyMinutes = /^\*\/(\d+)$/.exec(minute);
    if (everyMinutes && hour === "*") {
      const n = Number(everyMinutes[1]);
      if (n > 0) return { kind: "interval", seconds: n * 60 };
    }
    if (/^\d+$/.test(minute) && /^\d+$/.test(hour)) {
      return { kind: "calendar", hour: Number(hour), minute: Number(minute) };
    }
  }
  return { kind: "unsupported", reason: `launchd translation only supports "*/N * * * *" (every N minutes) or "M H * * *" (daily at H:M); got "${schedule}"` };
}

export function launchdLabel(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">): string {
  return `com.b2c-app-builder.${options.workspaceSlug}.${options.runtime}`;
}

export function launchdPlistPath(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">, homeDir = os.homedir()): string {
  return path.join(homeDir, "Library", "LaunchAgents", `${launchdLabel(options)}.plist`);
}

/** Read-only readback for a managed LaunchAgent; does not accept a plist for another job. */
export function launchdPlistHasLabel(xml: string, label: string): boolean {
  return xml.includes(`<key>Label</key><string>${label}</string>`);
}

/** Exact rendered readback; a matching label alone is insufficient after a concurrent target or cadence edit. */
export function launchdPlistHasExactContent(xml: string, expectedXml: string): boolean {
  return xml === expectedXml;
}

export type LaunchdPlistResult = { ok: true; xml: string } | { ok: false; error: string };

export function renderLaunchdPlist(options: ScheduleOptions): LaunchdPlistResult {
  const translated = translateCronToLaunchd(options.schedule);
  if (translated.kind === "unsupported") return { ok: false, error: translated.reason };
  const label = launchdLabel(options);
  const scheduleXml =
    translated.kind === "interval"
      ? `  <key>StartInterval</key>\n  <integer>${translated.seconds}</integer>\n`
      : `  <key>StartCalendarInterval</key>\n  <dict>\n    <key>Hour</key><integer>${translated.hour}</integer>\n    <key>Minute</key><integer>${translated.minute}</integer>\n  </dict>\n`;
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/env</string>
    <string>tsx</string>
    <string>${options.wrapperPath}</string>
  </array>
  <key>StandardOutPath</key><string>${options.logPath}</string>
  <key>StandardErrorPath</key><string>${options.logPath}</string>
${scheduleXml}  <key>RunAtLoad</key><false/>
</dict>
</plist>
`;
  return { ok: true, xml };
}

// --- claude sandbox check ------------------------------------------------------------------
//
// Claude Code reads sandbox state from `.claude/settings.json`'s `sandbox.enabled` field, never
// from a CLI flag (https://code.claude.com/docs/en/sandboxing). adapters/claude.ts's
// buildHeadlessCommand runs Bash with no `--sandbox`-style flag, so a scheduled claude session
// gets OS-level containment only if the workspace's settings.json already opts in. This check does
// not fail closed: it warns and records `sandboxed: false` on the install, but still installs the
// schedule — the founder decides whether to add the setting before or after scheduling.

export interface SandboxCheckResult {
  readonly sandboxed: boolean;
  readonly warning?: string;
}

/** Pure over the parsed settings.json so it stays fixture-safe; readClaudeSandboxSetting below wires it to the real file. */
export function checkClaudeSandboxSetting(settingsJson: unknown): SandboxCheckResult {
  const settings = typeof settingsJson === "object" && settingsJson !== null ? (settingsJson as Record<string, unknown>) : undefined;
  const sandbox = typeof settings?.["sandbox"] === "object" && settings["sandbox"] !== null ? (settings["sandbox"] as Record<string, unknown>) : undefined;
  if (sandbox?.["enabled"] === true) return { sandboxed: true };
  return {
    sandboxed: false,
    warning:
      'install-schedule: this workspace\'s .claude/settings.json does not set "sandbox": { "enabled": true }. ' +
      "A scheduled claude session runs Bash with no OS-level containment until it does. " +
      'Fix: set "sandbox": { "enabled": true, "failIfUnavailable": true } in that file. Installing the schedule anyway — sandboxed: false.',
  };
}

function readClaudeSandboxSetting(workspaceDir: string): SandboxCheckResult {
  const settingsPath = path.join(workspaceDir, ".claude", "settings.json");
  if (!existsSync(settingsPath)) return checkClaudeSandboxSetting(undefined);
  try {
    return checkClaudeSandboxSetting(JSON.parse(readFileSync(settingsPath, "utf8")));
  } catch {
    return checkClaudeSandboxSetting(undefined);
  }
}

// --- CLI ---------------------------------------------------------------------------------------

function fail(message: string): never {
  console.error(`install-schedule: ${message}`);
  process.exit(1);
}

function buildOptions(argv: string[]): {
  options: ScheduleOptions;
  mechanism: ScheduleMechanism;
  apply: boolean;
  uninstall: boolean;
  approvalId?: string;
} {
  const flags = parseFlags(argv, [
    { flags: ["--workspace", "--target"], key: "workspace" },
    { flags: ["--runtime"], key: "runtime", kind: "string" },
    { flags: ["--schedule"], key: "schedule", kind: "string" },
    { flags: ["--brief"], key: "brief" },
    { flags: ["--mechanism"], key: "mechanism", kind: "string" },
    { flags: ["--wall-clock-seconds"], key: "wallClockSeconds", kind: "number" },
    { flags: ["--skill-root"], key: "skillRoot" },
    { flags: ["--log"], key: "log" },
    { flags: ["--apply"], key: "apply", kind: "boolean" },
    { flags: ["--uninstall"], key: "uninstall", kind: "boolean" },
    { flags: ["--approval"], key: "approval", kind: "string" },
  ]);

  const workspaceDir = flagString(flags, "workspace")
    ? path.resolve(process.env.B2C_APP_BUILDER_CALLER_CWD?.trim() || process.cwd(), expandHome(flagString(flags, "workspace")!))
    : undefined;
  if (!workspaceDir) fail("--workspace <business-workspace-dir> is required.");
  const runtime = flagString(flags, "runtime") as RuntimeId | undefined;
  if (!runtime || !founderFacingRuntimeIds.includes(runtime))
    fail(`--runtime ${founderFacingRuntimeIds.join("|")} is required (inline is a fixture-only shape, never scheduled).`);
  const schedule = flagString(flags, "schedule");
  if (!schedule) fail('--schedule "<5-field cron expression>" is required, e.g. "*/30 * * * *".');
  const briefPath = flagString(flags, "brief") ? path.resolve(expandHome(flagString(flags, "brief")!)) : path.join(workspaceDir!, "brief.json");
  const skillRoot = path.resolve(expandHome(flagString(flags, "skillRoot") ?? defaultSkillRoot));
  const wallClockSeconds = flagNumber(flags, "wallClockSeconds") ?? 1800;
  const workspaceSlug = path.basename(workspaceDir!);
  const scheduleDir = path.join(workspaceDir!, "schedule");
  const wrapperPath = path.join(scheduleDir, `run-${runtime}.mts`);
  const logPath = flagString(flags, "log") ? path.resolve(expandHome(flagString(flags, "log")!)) : path.join(scheduleDir, `run-${runtime}.log`);
  const mechanism = (flagString(flags, "mechanism") as ScheduleMechanism | undefined) ?? "cron";
  if (mechanism !== "cron" && mechanism !== "launchd") fail(`--mechanism must be "cron" or "launchd", got "${mechanism}".`);

  return {
    options: { workspaceDir: workspaceDir!, runtime, schedule, briefPath, wallClockSeconds, skillRoot, wrapperPath, logPath, workspaceSlug },
    mechanism,
    apply: flagBoolean(flags, "apply"),
    uninstall: flagBoolean(flags, "uninstall"),
    approvalId: flagString(flags, "approval"),
  };
}

/**
 * Host mutation is a founder-only schedule effect. The CLI flag is not itself authority: an
 * apply must name the canonical scheduled-autonomy approval and that approval must be currently
 * approved in the workspace run state. Dry runs intentionally do not require it.
 */
export function assertScheduleApproval(workspaceDir: string, approvalId: string | undefined): void {
  if (approvalId !== scheduledAutonomyApprovalId) {
    throw new Error(`install-schedule.schedule_authority_required: --apply requires --approval ${scheduledAutonomyApprovalId}`);
  }
  const runStatePath = path.join(workspaceDir, "run", "run-state.json");
  let run: ReturnType<typeof loadRunState>;
  try {
    run = loadRunState(runStatePath);
  } catch {
    throw new Error("install-schedule.schedule_authority_unavailable: the workspace has no readable current run state; complete the scheduled-autonomy approval first");
  }
  if (run.approvals[scheduledAutonomyApprovalId] !== "approved") {
    throw new Error("install-schedule.schedule_authority_pending: the current scheduled-autonomy founder approval is not approved");
  }
}

function readCrontab(): string {
  const result = spawnSync("crontab", ["-l"], { encoding: "utf8" });
  // An empty/never-configured crontab exits nonzero on most platforms — that's "no crontab yet", not an error.
  if (result.status !== 0) return "";
  return result.stdout ?? "";
}

function writeCrontab(content: string): void {
  const result = spawnSync("crontab", ["-"], { input: content, encoding: "utf8" });
  if (result.status !== 0) throw new Error(`crontab install failed: ${result.stderr || result.stdout || `exit ${String(result.status)}`}`);
}

export function scheduleMutationLockPath(homeDir = os.homedir()): string {
  return path.join(homeDir, ".config", "b2c-app-builder", "schedule.lock");
}

export function withScheduleMutationLock<T>(operation: () => T, homeDir = os.homedir()): T {
  const ownerSessionId = `schedule:${process.pid}:${randomUUID()}`;
  const lockPath = scheduleMutationLockPath(homeDir);
  const acquired = acquireLock(lockPath, { ownerSessionId, retries: 0, ttlSeconds: 120 });
  if (!acquired.ok) {
    throw new Error(acquired.reason === "held" ? "install-schedule.schedule_lock_held" : "install-schedule.schedule_lock_stale_unverified");
  }
  try {
    return operation();
  } finally {
    releaseLock(lockPath, ownerSessionId);
  }
}

function runMain(): void {
  const { options, mechanism, apply, uninstall, approvalId } = buildOptions(process.argv.slice(2));
  if (!uninstall) {
    const compatible = loadWorkspaceCatalog(options.workspaceDir);
    if (!compatible.ok) fail(renderCatalogRefusal(compatible.refusal));
  }

  if (apply) {
    try {
      assertScheduleApproval(options.workspaceDir, approvalId);
    } catch (error) {
      fail(error instanceof Error ? error.message : String(error));
    }
  }

  const sandboxCheck = !uninstall && options.runtime === "claude" ? readClaudeSandboxSetting(options.workspaceDir) : undefined;
  if (sandboxCheck?.warning) console.warn(sandboxCheck.warning);
  const sandboxSuffix = sandboxCheck ? ` (sandboxed: ${String(sandboxCheck.sandboxed)})` : "";

  if (mechanism === "cron") {
    if (!apply) {
      console.log(`install-schedule: DRY RUN (${uninstall ? "uninstall" : "install"}, cron) — would write the wrapper script and update the user crontab.`);
      console.log(`  wrapper: ${options.wrapperPath}`);
      if (!uninstall) console.log(`  crontab line: ${renderCrontabLine(options)}`);
      console.log(`  would remove any crontab line tagged "# ${crontabSignature(options)}"`);
      console.log(`  verify after --apply with: crontab -l | grep ${JSON.stringify(crontabSignature(options))}`);
      console.log(`  approval required for --apply: ${scheduledAutonomyApprovalId}`);
      if (sandboxCheck) console.log(`  sandboxed: ${String(sandboxCheck.sandboxed)}`);
      return;
    }
    try {
      withScheduleMutationLock(() => {
        mkdirSync(path.dirname(options.wrapperPath), { recursive: true });
        const current = readCrontab();
        const result = uninstall ? applyCrontabUninstall(current, options) : applyCrontabInstall(current, options);
        if (!uninstall) writeFileSync(options.wrapperPath, renderWrapperScript(options), { mode: 0o755 });
        writeCrontab(result.nextContent);
        const readBackContent = readCrontab();
        const readBack = uninstall
          ? crontabHasWorkspaceSignature(readBackContent, options.workspaceSlug)
          : crontabHasExactLine(readBackContent, "line" in result ? result.line : "");
        if (uninstall ? readBack : !readBack) {
          throw new Error(
            `cron readback did not confirm the requested ${uninstall ? "removal" : "installation"} for ${options.workspaceSlug}/${options.runtime}`,
          );
        }
      });
    } catch (error) {
      fail(error instanceof Error ? error.message : String(error));
    }
    console.log(
      `install-schedule: ${uninstall ? "removed" : "installed"} and verified the cron entry for ${options.workspaceSlug}/${options.runtime}.${sandboxSuffix}`,
    );
    return;
  }

  // launchd
  const plist = renderLaunchdPlist(options);
  if (!plist.ok) fail(plist.error);
  const plistPath = launchdPlistPath(options);
  if (!apply) {
    console.log(
      `install-schedule: DRY RUN (${uninstall ? "uninstall" : "install"}, launchd) — would write the wrapper script and ${uninstall ? "unload + remove" : "write + load"} the LaunchAgent plist.`,
    );
    console.log(`  wrapper: ${options.wrapperPath}`);
    console.log(`  plist:   ${plistPath}`);
    if (!uninstall) console.log(plist.xml);
    if (sandboxCheck) console.log(`  sandboxed: ${String(sandboxCheck.sandboxed)}`);
    return;
  }
  try {
    withScheduleMutationLock(() => {
      if (uninstall) {
        for (const target of [plistPath]) {
          if (existsSync(target)) {
            const unloaded = spawnSync("launchctl", ["unload", target], { encoding: "utf8" });
            if (unloaded.status !== 0) throw new Error(`launchctl unload failed: ${unloaded.stderr || unloaded.stdout || `exit ${String(unloaded.status)}`}`);
            unlinkSync(target);
          }
        }
        if (existsSync(plistPath)) throw new Error(`launchd readback did not confirm removal for ${options.workspaceSlug}/${options.runtime}`);
        return;
      }
      mkdirSync(path.dirname(options.wrapperPath), { recursive: true });
      writeFileSync(options.wrapperPath, renderWrapperScript(options), { mode: 0o755 });
      mkdirSync(path.dirname(plistPath), { recursive: true });
      writeFileSync(plistPath, plist.xml);
      const loaded = spawnSync("launchctl", ["load", plistPath], { encoding: "utf8" });
      if (loaded.status !== 0) throw new Error(`launchctl load failed: ${loaded.stderr || loaded.stdout || `exit ${String(loaded.status)}`}`);
      const installedXml = readFileSync(plistPath, "utf8");
      if (!launchdPlistHasExactContent(installedXml, plist.xml)) {
        throw new Error(`launchd readback did not confirm the exact managed plist for ${options.workspaceSlug}/${options.runtime}`);
      }
    });
  } catch (error) {
    fail(error instanceof Error ? error.message : String(error));
  }
  if (uninstall) {
    console.log(`install-schedule: removed and verified the launchd job for ${options.workspaceSlug}/${options.runtime}.`);
    return;
  }
  console.log(`install-schedule: installed and verified the launchd job for ${options.workspaceSlug}/${options.runtime}.${sandboxSuffix}`);
}

if (isMainModule(import.meta.url)) {
  runMain();
}
