import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { extensionSchema } from "../contracts/extensions/contract.js";
import { compositionSchema, PUBLIC_OPERATIONS } from "../contracts/public-api/contract.js";
import { issue, reportAndExit, type Issue } from "./lib/launch-state.js";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../contracts/public-api");
const check = process.argv.slice(2).includes("--check");
const issues: Issue[] = [];
function emit(name: string, content: string): void {
  const file = path.join(root, name);
  let current: string | undefined;
  try {
    current = readFileSync(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (current === content) return;
  if (check) {
    issues.push(
      issue("error", "public_api.stale_projection", `Stale public contract projection: ${name}`, file, { fixHint: "Run npm run render:public-api." }),
    );
    return;
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
}
function jsonSchema(schema: z.ZodType, output = false): string {
  const value = z.toJSONSchema(schema, { target: "draft-2020-12", io: output ? "output" : "input" });
  // Consumers must tolerate additive output fields; authored inputs stay strict.
  function additive(node: unknown): void {
    if (!node || typeof node !== "object") return;
    if (!Array.isArray(node) && "type" in node && node.type === "object") (node as Record<string, unknown>).additionalProperties = true;
    for (const child of Object.values(node)) additive(child);
  }
  if (output) additive(value);
  return JSON.stringify(value, null, 2) + "\n";
}
emit("schemas/composition.schema.json", jsonSchema(compositionSchema));
emit("../extensions/schemas/extension.schema.json", jsonSchema(extensionSchema));
for (const operation of PUBLIC_OPERATIONS) {
  emit(`schemas/${operation.id}.input.schema.json`, jsonSchema(operation.inputSchema));
  emit(`schemas/${operation.id}.result.schema.json`, jsonSchema(operation.outputSchema, true));
}
emit(
  "REFERENCE.md",
  [
    "# Public API v1 reference",
    "",
    "Generated by `tooling/render-public-api.ts` from `contracts/public-api/contract.ts`. Do not edit this projection.",
    "",
    "The public API version is `b2c/v1`. Engine/package versions and entity versions are separate. This stable boundary covers discovery, declaration preview, registered workspace reads, and explicit local package activation. Execution support is reported separately.",
    "",
    ...PUBLIC_OPERATIONS.flatMap((op) => [
      `## ${op.id}`,
      "",
      op.description,
      "",
      `- CLI: \`b2c ${op.cli}\``,
      op.mcp ? `- MCP: \`${op.mcp}\`` : "- MCP: unavailable (CLI operator only)",
      `- [Input schema](schemas/${op.id}.input.schema.json)`,
      `- [Result schema](schemas/${op.id}.result.schema.json)`,
      "",
    ]),
    "## Composition",
    "",
    "- [Authored composition schema](schemas/composition.schema.json)",
    "- [Subscription preview example](examples/subscription-app.json)",
    "- [Mobile app capture preview example](examples/mobile-app-capture.json)",
    "",
    "Every result has `apiVersion`, `requestId`, `ok`, and `warnings`; success has `data`, failure has `error`. Error codes are machine-readable. Request IDs are correlation identifiers, not execution receipts. Consumers must ignore unknown output fields and handle unknown error codes as failures. Authored input fields are strict.",
    "",
    "A preview validates declarations only. `canApply: false` and explicit blockers mean the composition cannot run. `proposalDigest` identifies a proposal; it is not an authorization, workspace revision, or apply receipt. Connection references contain no credentials. No files, provider state, authority, or evidence are inspected by the shared preview service.",
    "",
  ].join("\n"),
);
if (check) reportAndExit("Public API projections", issues);
else console.log("Rendered public API schemas and reference.");
